### ISSUE TITLE
Using Dart googleapis_auth (0.2.2) to authorize Admin SDK Directory API in Google Apps domains with service account

### ISSUE THREAD

**Issue by goranj** [dart-lang/googleapis_auth#14]
I asked this question on SO:

http://stackoverflow.com/questions/28284509/using-dart-googleapis-auth-0-2-2-to-authorize-admin-sdk-directory-api-in-googl

Maybe someone here can help?

**Comment by Scarygami** [comment]
There seems to be a pull request for that functionality already.
https://github.com/dart-lang/googleapis_auth/pull/11

Maybe you can test if their fork works for you:
https://github.com/ikamman/googleapis_auth/

**Comment by goranj** [comment]
Works like a breeze!

I'm not an Git ninja. Far from it actually. Will this eventually be merged?

Thanks

**Comment by goranj** [comment]
I'm now using googleapis_auth 0.2.3 and it works fine.
https://pub.dartlang.org/packages/googleapis_auth
Thanks a lot!
