### ISSUE TITLE
get Token

### ISSUE THREAD

**Issue by ysoofiyani** [dart-lang/googleapis_auth#52]
by below code I can not get token. it is null. why ?
what should be scopes? I think my issue is for scopes.

createImplicitBrowserFlow(id, scopes).then((BrowserOAuth2Flow flow){
      flow.obtainAccessCredentialsViaUserConsent().then((AccessCredentials credentials){
        print(credentials.idToken);
       // print(credentials.accessToken.data);
        flow.close();
      });
    });

**Comment by jonasfj** [comment]
You'll need to specify `responseTypes` in `obtainAccessCredentialsViaUserConsent(responseTypes: [ResponseType.idToken])`, see:
https://pub.dartlang.org/documentation/googleapis_auth/latest/googleapis_auth.auth_browser/BrowserOAuth2Flow/obtainAccessCredentialsViaUserConsent.html

If you want to improve examples, PRs are welcome :)
