### ISSUE TITLE
Docs unclear

### ISSUE THREAD

**Issue by jordyvandomselaar** [dart-lang/googleapis_auth#54]
I'm following the `Installed/Console Application` `or obtain an authenticated HTTP client via` flow.

You show the following code snippet:

```
import "package:googleapis_auth/auth_io.dart";

...

var id = new ClientId("....apps.googleusercontent.com", "...");
var scopes = [...];

clientViaUserConsent(id, scopes, prompt).then((AuthClient client) {
  // Authenticated and auto refreshing client is available in [client].
  // ...
  client.close();
});

void prompt(String url) {
  print("Please go to the following URL and grant access:");
  print("  => $url");
  print("");
}
```

That part works now, my console shows an url to open and I get a consent screen. The docs don't show what to do after though. What do I do after hitting the consent button? My browser is redirected to `localhost` which shows an error because it couldn't find that url.

According to the docs the redirect uri is generated automatically:

> The redirect URIs for the automatic and manual flow will be configured automatically.

I honestly don't get the docs. I have no clue what I'm doing.

**Comment by jonasfj** [comment]
If you have suggestions for how to improve the docs, please file a PR -- they are by no means perfect.

**Comment by kushal-g** [comment]
I'm facing the same issue right now. What am I doing wrong?
