### ISSUE TITLE
Fails when used with dart2js under Firebase Functions

### ISSUE THREAD

**Issue by jan-pavlovsky** [dart-lang/googleapis_auth#76]
When used in code run under Firebase Functions (using firebase_functions_interop package), I get the error:
`ReferenceError: XMLHttpRequest is not defined`
when trying to call
`obtainAccessCredentialsViaServiceAccount` or `clientViaServiceAccount`

I tried adding polyfills using js interop and so on, but nothing seems to work

**Comment by jonasfj** [comment]
this is compiling with `dart2js` and running on top of node.js

I don't think this is in scope of this project. If someone wants to support we might accept a minor PR if fixing it easy to do. But this ideally better maintained in a separate package.
