### ISSUE TITLE
Get new access token using refresh Token

### ISSUE THREAD

**Issue by Errechydy** [dart-lang/googleapis_auth#77]
I searched a lot about how to use `refreshToken` to get new access token but i could't find anything.
Here is the code i use to get user's credentials:
```
var authClient = await clientViaUserConsent(
    ClientId(_clientId, _clientSecret), 
    _scopes,
    (url) { launch(url);}
);
//Save Credentials
await storage.saveCredentials(authClient.credentials.accessToken,
    authClient.credentials.refreshToken);
return authClient;
```

After i get the user's credentials, i save them locally so i can use them later,
```
return authenticatedClient(
        http.Client(),
        AccessCredentials(
            AccessToken(credentials["type"], credentials["data"],
                DateTime.tryParse(credentials["expiry"])),
            credentials["refreshToken"],
            _scopes)
);
```

I don't know if there is a way to make use of the `refreshToken` to get new access token (which expires in one hour), it's a bad user experience to ask the user to grant you the access every single hour

**Comment by zhuwei** [comment]
I have the same problem

**Comment by zhuwei** [comment]
I know how
```
/// Tries to obtain refreshed [AccessCredentials] based on [credentials] using
/// [client].
Future<AccessCredentials> refreshCredentials(
    ClientId clientId, AccessCredentials credentials, Client client) async
```
Get new credentials through refresh_token

**Comment by Errechydy** [comment]
@zhuwei Thanks a lot, it worked.
